### ISSUE TITLE
Some components in DatFolder are broken

### ISSUE THREAD

**Issue by rdrgn** [claus/react-dat-gui#16]
I ran the example by `npm run start`.
Then, for example, the slider of `DatNumber` and the colored rectangle `DatColor` in `DatFolder` are not displayed.

![image](https://user-images.githubusercontent.com/9990535/52326498-39e8da80-2a2c-11e9-90ce-99e22c79b7a6.png)

**Comment by rohan-deshpande** [comment]
Hey thanks for pointing this out, was possibly broken by https://github.com/claus/react-dat-gui/pull/7, if you don't mind reverting to before that PR and checking the demo to see that would be super helpful!

**Comment by rdrgn** [comment]
Before https://github.com/claus/react-dat-gui/commit/610d494ac5cc00ad19f82d08701d330a525f36c7, it seems to work normally. So we should review #7 again.

**Comment by rohan-deshpande** [comment]
Yah I thought so, I knew there was a reason I was doing it.

Would love to have tests for this repo, I just don’t have the time. Thanks for raising the PR, I’ll review shortly.

**Comment by mannytan** [comment]
I'm still getting an error for children inside DatFolder. I'm getting this below when updating DatString.

`Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components`

removing DatFolder works.

**Comment by rohan-deshpande** [comment]
Are you testing out the develop branch or from within your app? I’m not sure if the patch has been published to npm yet.

**Comment by claus** [comment]
I just published 2.2.0.

**Comment by rohan-deshpande** [comment]
@mannytan can you confirm the issue is happening in `v2.2.0`?

**Comment by mannytan** [comment]
Looks like it's working again in 2.2.0, thanks!
