### ISSUE TITLE
labelWidth doesn't affect DatBoolean e.g. checkbox label width

### ISSUE THREAD

**Issue by GCDeveloper** [claus/react-dat-gui#30]
labelWidth doesn't affect DatBoolean e.g. checkbox label width, it remains at 40% width default.
This is the component which could use labelWidth the most.

**Comment by tim-soft** [comment]
Fix is in https://github.com/claus/react-dat-gui/pull/33

Which would let you do something like this:
```
<DatGUI labelWidth="40%">
    <DatBoolean labelWidth="200px" />
</DatGUI>
```
