### ISSUE TITLE
Defect, or missing docs?

### ISSUE THREAD

**Issue by mariusk** [claus/react-dat-gui#43]
The default styling was missing when using the module as documented. I had to:

`import 'react-dat-gui/dist/index.css';`

in my main component to get the default styling to work.

**Comment by psullivan6** [comment]
I also ran into this issue, but found that the example code provided used the `@tim-soft/react-dat-gui` npm package, which worked as expected. I'm not sure if it's an intentional change, but I opted to use that version of the package to import the least amount of additional code.

**Comment by cdedreuille** [comment]
Any update on this one @rohan-deshpande?

**Comment by rohan-deshpande** [comment]
I'll get this done in #47

**Comment by rohan-deshpande** [comment]
Resolved by #51

**Comment by zzusunjs** [comment]
Met the same problem at `"react-dat-gui": "^4.0.3",` , 2020.11.15

**Comment by nhtranngoc** [comment]
Same problem, Feb 2021

**Comment by pramodmd** [comment]
any update on this? . June 2021, same problem :(

**Comment by uoon-dev** [comment]
Same problem, Feb 2022

**Comment by Wandergin** [comment]
Kind of worked the problem around by creating a file out of [this css file](https://claus.github.io/react-dat-gui/_next/static/css/styles.5b7401e1.chunk.css) and importing it at the root component (next.js, react-dat-gui ^4.1.1). Fixing this should be a priority @rohan-deshpande, appreciate it!
