### ISSUE TITLE
feature request: support title setting

### ISSUE THREAD

**Issue by marswong** [claus/react-dat-gui#5]
it would be perfect if we can set a title of the toolbar, the API could be looked like:

```javascript
<DatGui title="xxx" />

// or

<DatGui>
  <DatTitle path="xxx" />
</DatGui>
```

Thank you :)

**Comment by rohan-deshpande** [comment]
Hmm is this mutable though? If not why not just render a div before `DatGui`. If it's mutable, you have `DatString`. 

`DatFolder` is similar to this but provides some UX functionality.

**Comment by marswong** [comment]
it should be immutable and it's ok to render a div before `DatGui`, just we need to hard code on that, not so elegant. I think your style design is awesome, so it would be great to support a center aligned title on the top of `DatGui` children. Thank you :)

**Comment by rohan-deshpande** [comment]
So I guess you kind of want a `DatSection` component? 

I can kind of see the use but that's also what `DatFolder` is for...

I'd lean away from putting in controllers that don't control anything, the lib could get too bloated if we start doing that.

**Comment by marswong** [comment]
yes, maybe at present it's ok to hack on the style of `DatFolder`
