### ISSUE TITLE
Publish v4.0.1 to npm

### ISSUE THREAD

**Issue by rohan-deshpande** [claus/react-dat-gui#52]
@claus Please publish the latest version when you've got a minute, would also appreciate publishing rights so I can do this without bugging you in future!

**Comment by claus** [comment]
@rohan-deshpande What's your username on npm?

**Comment by rohan-deshpande** [comment]
rohandeshpande

**Comment by claus** [comment]
<img width="382" alt="Screen Shot 2020-04-23 at 22 20 55" src="https://user-images.githubusercontent.com/2277/80164996-cab7c180-85b0-11ea-9f4f-ce1f4b88b86e.png">

🎉
