### ISSUE TITLE
Library console logs "dude" when using a DatBoolean

### ISSUE THREAD

**Issue by disambiguator** [claus/react-dat-gui#54]
Offending code is here: https://github.com/claus/react-dat-gui/blob/master/dist/index.es.js#L457

**Comment by rohan-deshpande** [comment]
LOL okay, PRs welcome ;) will get to this in the next round of changes otherwise

**Comment by claus** [comment]
Fixed, and deployed 4.0.2, thanks!

**Comment by disambiguator** [comment]
Hah no problem :)
